# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HAGeomtryFixer
                                 A QGIS plugin
 This plugin will fix your geometry in the original layer without create new temp layer and remove any duplicated vertices.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-12
        copyright            : (C) 2024 by Lei Ding
        email                : lei.ding@headlandarchaeology.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HAGeomtryFixer class from file HAGeomtryFixer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ha_geomtry_fixer import HAGeomtryFixer
    return HAGeomtryFixer(iface)
