# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HAGeomtryFixer
                                 A QGIS plugin
 This plugin will fix your geometry in the original layer without create new temp layer and remove any duplicated vertices.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-04-12
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Lei Ding
        email                : lei.ding@headlandarchaeology.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsProject, QgsVectorLayer, QgsFeatureRequest, QgsExpression, edit
from qgis.utils import iface
from qgis.gui import QgsMessageBar, QgsVertexMarker
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QVBoxLayout, QLabel
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QDialog, QVBoxLayout, QLabel, QDialogButtonBox
from qgis.core import QgsApplication
from qgis.core import QgsProcessingFeatureSourceDefinition

# Now you can use QgsProcessingFeatureSourceDefinition in your code

# Access QGIS Processing through QgsApplication



# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .ha_geomtry_fixer_dialog import HAGeomtryFixerDialog
import os.path
import processing
class HAGeomtryFixerDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        
        layout = QVBoxLayout(self)
        
        # Add label with message
        #First Line
        message_label = QLabel("Please make sure you have chosen all layers you want to fix.")
        message_label.setAlignment(Qt.AlignCenter)
        layout.addWidget(message_label)

        # Add empty QLabel for space line
        space_label = QLabel("")
        layout.addWidget(space_label)

        # Add label with second message
        additional_message_label1 = QLabel("Please make sure all layers selected are editable.")
        additional_message_label1.setAlignment(Qt.AlignCenter)
        layout.addWidget(additional_message_label1)

        space_label2 = QLabel("")
        layout.addWidget(space_label2)

        # Add label with second message
        additional_message_label2 = QLabel("Features that have been fixed will be selected in the layer.")
        additional_message_label2.setAlignment(Qt.AlignCenter)
        layout.addWidget(additional_message_label2)
        
        # Add QDialogButtonBox with Ok and Cancel buttons
        button_box = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        button_box.accepted.connect(self.accept)
        button_box.rejected.connect(self.reject)
        layout.addWidget(button_box)

        # Set the layout
        self.setLayout(layout)


class HAGeomtryFixer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'HAGeomtryFixer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&HA-Geometry Fixer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('HAGeomtryFixer', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/ha_geomtry_fixer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'HA-Geometry Fixer'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&HA-Geometry Fixer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = HAGeomtryFixerDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            selected_layers = iface.layerTreeView().selectedLayers()  
            for layer in selected_layers:
                result_fixed = processing.run("native:fixgeometries", {
                            'INPUT': QgsProcessingFeatureSourceDefinition(layer.source()),
                            'METHOD':1,
                            'OUTPUT':'TEMPORARY_OUTPUT'
                        })
                fixed = result_fixed['OUTPUT']
                fixed.setName("fixed")
                QgsProject.instance().addMapLayer(fixed)
                
                with edit(layer):
                    layer.dataProvider().deleteFeatures(layer.allFeatureIds())

                fixed.selectAll()
                iface.mapCanvas().refresh()
            
                layer.startEditing()
                
                iface.copySelectionToClipboard(fixed)
                iface.pasteFromClipboard(layer)
                layer.commitChanges()
                
                QgsProject.instance().removeMapLayer(fixed.id())

                
            iface.mapCanvas().refresh()
            QMessageBox.information(None, "Geometry Fixer", "All selected layers' geometry are fixed.")

