# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ha_z_fixer_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from qgis.PyQt import uic
from PyQt5 import QtCore, QtGui, QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ha_z_fixer_dialog_base.ui'))



class HAZFixerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(HAZFixerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
    """
    def setupUi(self, HAZFixerDialogBase):
        HAZFixerDialogBase.setObjectName("HAZFixerDialog")
        HAZFixerDialogBase.resize(700, 300)
        HAZFixerDialogBase.setMinimumSize(QtCore.QSize(700, 300))
        HAZFixerDialogBase.setMaximumSize(QtCore.QSize(800, 400))
        self.gridLayout_3 = QtWidgets.QGridLayout(HAZFixerDialogBase)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_box = QtWidgets.QDialogButtonBox(HAZFixerDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout_3.addWidget(self.button_box, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(HAZFixerDialogBase)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(HAZFixerDialogBase)
        self.button_box.accepted.connect(HAZFixerDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(HAZFixerDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HAZFixerDialogBase)

    def retranslateUi(self, HAZFixerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        HAZFixerDialogBase.setWindowTitle(_translate("HAZFixerDialogBase", "HA-Z Fixer"))
        self.groupBox.setTitle(_translate("HAZFixerDialogBase", "Info of HA-Z Fixer"))
        self.label.setText(_translate("HAZFixerDialogBase", "This plugin will fix your z value by cloest vertex.\n"
"It will fail if none of the vextex in the selected layer has z value. \n"
"Please make sure you have selected all layers you want to fix. \n"
"Please make sure layers you selected are editable.\n"
"Tip:Open Python Console will help you to see details of features that are being fixing."))
        self.label_2.setText(_translate("HAZFixerDialogBase", "Plugin made by Headland - TechS - GIS Team \n"
"Please contact through Teams - Support channel or email Hellpsurvey if you need any help."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HAZFixerDialogBase = QtWidgets.QDialog()
    ui = Ui_HAZFixerDialogBase()
    ui.setupUi(HAZFixerDialogBase)
    HAZFixerDialogBase.show()
    sys.exit(app.exec_())
"""